name: "n8n - Workflow Automation"
description: "This is an n8n add-on for Home Assistant to automate workflows."
version: "1.0.0"
slug: "n8n"
init: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: "https://github.com/fwartner/homeassistant-addons/tree/main/n8n"
options:
  webhook_tunnel_url:
    name: Webhook URL
    description: "The webhook URL to use for n8n."
    required: false
    type: "str"
  n8n_port:
    name: Port
    description: "The port to use for n8n."
    required: false
    type: "str"
    default: "5678"
